#Rename this file to application.yml and customize with your specific properties

micronaut:
  application:
    name: fermbot

fermbot:
  suffix: test01
  pytilt-script-path: python
  brewfather:
    enabled: true
    customStreamId: #enter string after id= on brewfather page (e.g. 23GDSfjdl2984)
  ds18b20:
    enabled: true
  heater:
    enabled: true
    pin-name: GPIO 4
  hysteresis:
    lower: 1F
    upper: 1F
  cooler:
    enabled: true
    pin-name: GPIO 5
  tilt:
    enabled: true
  simulation:
    step:
      duration: 10ms
  #add a b c for ds18B20 error correction
  #add gravity stability, i.e. how long does gravity have to be within 1 or 2 points to be considered reach (i.e. 12 hours) (in ISO-8601 format)

